Repository vinitshahdeo/Hacktoberfest2021, pull requests merged in 2021-09, with the labels that each got.

#141 Chore: Add Beginner-friendly repositories
  README.md
Labels: documentation

#145 Chore: Add project
  explore/PROJECTS.md
Labels: documentation

#160 chore: Add projects.
  explore/PROJECTS.md
Labels: enhancement, Chore

#161 Added me to the mentor's list
  MENTORS.md
Labels: Chore

#172 Added praveenscience pic.
  assets/pictures/praveenscience.png
Labels: Chore

#173 added my picture
  assets/pictures/AnirudhPanda.jpg
Labels: Chore

#178 added 3 project and my picture
  assets/pictures/yash-2115.jpg
  explore/PROJECTS.md
Labels: Chore

#186 [Project] Added MaskDetectionWebApp
  explore/PROJECTS.md
Labels: Chore

#204 Add Heel2Toe in PROJECTS.md
  explore/PROJECTS.md
Labels: Chore

#210 chore: add projects.
  explore/PROJECTS.md
Labels: Chore

#213 chore: Add projects
  explore/PROJECTS.md
Labels: Chore

#212 Added a new project "LeafLet"
  explore/PROJECTS.md
Labels: Chore

#214 add : issue for Heel2Toe
  explore/ISSUES.md
Labels: documentation

#216 Added a beginner friendly issue
  explore/ISSUES.md
Labels: Chore

#227 fix: link
  README.md
Labels: Chore

#228 project added
  explore/PROJECTS.md
Labels: Chore

#226 Add Password Knitter Project
  explore/PROJECTS.md
Labels: Chore

#231 Added New Project & Issue For Android
  assets/pictures/yogeshpaliyal.png
  explore/ISSUES.md
  explore/PROJECTS.md
Labels: Chore

#233 Update PROJECTS.md
  explore/PROJECTS.md
Labels: Chore

#201 Add issue for crossfire
  explore/ISSUES.md
Labels: Chore

#236 [AtharvaShirdhankar]Adding image file and Two Projects
  assets/pictures/Atharva_Shirdhankar.png
  explore/PROJECTS.md
Labels: Chore

#241 Update issues.md
  explore/ISSUES.md
Labels: Chore

#248 fix: discord link.
  README.md
Labels: fix

#250 added few repositories of moja global community
  explore/PROJECTS.md
Labels: Chore

#260 added my photo in assets/pictures
  assets/pictures/KshitijDhyani.jpeg
Labels: Chore

#263 chore: add projects
  explore/PROJECTS.md
Labels: documentation, Chore

#264 Added new issue
  explore/ISSUES.md
Labels: Chore

#270 added few beginner friendly issues
  explore/ISSUES.md
Labels: Chore

#271 Added Project Repositories in Projects.md
  explore/PROJECTS.md
Labels: Chore

#279 Updated Projects.md
  explore/PROJECTS.md
Labels: Chore

#288 New issue added
  explore/ISSUES.md
Labels: Chore

#289 Chore: Added Mentor Pic
  assets/pictures/Parth_L.jpg
Labels: Chore

#292 Added 5 New beginner Friendly issues.
  explore/ISSUES.md
Labels: Chore

#313 Update PROJECTS.md
  explore/PROJECTS.md
Labels: Chore

#315 Added more projects and issues
  explore/ISSUES.md
  explore/PROJECTS.md
Labels: Chore

#317 Update PROJECTS.md
  explore/PROJECTS.md
Labels: Chore

#331 Added PROJECTS "OpenSource-for-Everyone"
  explore/PROJECTS.md
Labels: Chore

#332 Add new projects and issues
  explore/ISSUES.md
  explore/PROJECTS.md
Labels: Chore

#347 Added Porjects in PROJECTS.md
  explore/PROJECTS.md
Labels: Chore
